[profile.default]
src = "src"
out = "out"
libs = ["lib"]
allow_paths = ["../mUSD"]
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
    "mUSD/=../mUSD/src/"
]

[profile.ci.fuzz]
runs = 10_000
