[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "^3.0.4" }

[dependencies]
boundless-market = "1.2.0"
tokio = "1.48.0"

[package.metadata.risc0]
methods = ["guest"]
